from .unet import UNet
from .mini_unet import MiniUNet
from .micro_unet import MicroUNet
from .bigger_unet import BiggerUNet
from .fcn8s import FCN8s
from .fcn16s import FCN16s
from .fcn32s import FCN32s
from .deeplabv3_resnet50 import DeepLabV3ResNet50
from .deeplabv3_mobilenet import DeepLabV3MobileNet
from .deeplabv3_hrnetv2_32 import DeepLabV3HRNetV2W32
from .deeplabv3_hrnetv2_48 import DeepLabV3HRNetV2W48
from .deeplabv3_resnet101 import DeepLabV3ResNet101
